// Mocks generated by Mockito 5.4.5 from annotations
// in flow_mobile/test/data/repositories/transaction_repository_impl_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:flow_mobile/data/datasources/local/transaction_local_datasource.dart'
    as _i2;
import 'package:flow_mobile/data/datasources/remote/transaction_remote_datasource.dart'
    as _i5;
import 'package:flow_mobile/domain/entities/transaction.dart' as _i4;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [TransactionLocalDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockTransactionLocalDataSource extends _i1.Mock
    implements _i2.TransactionLocalDataSource {
  MockTransactionLocalDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<List<_i4.Transaction>> getTransactions(DateTime? date) =>
      (super.noSuchMethod(
        Invocation.method(
          #getTransactions,
          [date],
        ),
        returnValue:
            _i3.Future<List<_i4.Transaction>>.value(<_i4.Transaction>[]),
      ) as _i3.Future<List<_i4.Transaction>>);

  @override
  _i3.Future<List<_i4.Transaction>> getTransactionsFromTo(
    DateTime? fromDate,
    DateTime? toDate,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #getTransactionsFromTo,
          [
            fromDate,
            toDate,
          ],
        ),
        returnValue:
            _i3.Future<List<_i4.Transaction>>.value(<_i4.Transaction>[]),
      ) as _i3.Future<List<_i4.Transaction>>);

  @override
  _i3.Future<void> addTransaction(_i4.Transaction? transaction) =>
      (super.noSuchMethod(
        Invocation.method(
          #addTransaction,
          [transaction],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> clearTransactions() => (super.noSuchMethod(
        Invocation.method(
          #clearTransactions,
          [],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<List<_i4.Transaction>> getAllTransactions() => (super.noSuchMethod(
        Invocation.method(
          #getAllTransactions,
          [],
        ),
        returnValue:
            _i3.Future<List<_i4.Transaction>>.value(<_i4.Transaction>[]),
      ) as _i3.Future<List<_i4.Transaction>>);
}

/// A class which mocks [TransactionRemoteDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockTransactionRemoteDataSource extends _i1.Mock
    implements _i5.TransactionRemoteDataSource {
  MockTransactionRemoteDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<List<_i4.Transaction>> syncTransactions() => (super.noSuchMethod(
        Invocation.method(
          #syncTransactions,
          [],
        ),
        returnValue:
            _i3.Future<List<_i4.Transaction>>.value(<_i4.Transaction>[]),
      ) as _i3.Future<List<_i4.Transaction>>);

  @override
  _i3.Future<void> uploadTransaction(_i4.Transaction? transaction) =>
      (super.noSuchMethod(
        Invocation.method(
          #uploadTransaction,
          [transaction],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<List<_i4.Transaction>> downloadTransactions() =>
      (super.noSuchMethod(
        Invocation.method(
          #downloadTransactions,
          [],
        ),
        returnValue:
            _i3.Future<List<_i4.Transaction>>.value(<_i4.Transaction>[]),
      ) as _i3.Future<List<_i4.Transaction>>);

  @override
  _i3.Future<void> deleteTransaction(String? transactionId) =>
      (super.noSuchMethod(
        Invocation.method(
          #deleteTransaction,
          [transactionId],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);
}
