spring:
  application:
    name: flow
  cloud:
    vault:
      uri: http://localhost:8200
      scheme: http
      authentication: token
      token: dev-root-token
      kv:
        enabled: true
        backend: secret
        backend-version: 2
        default-context: application
        application-name: ${spring.application.name}
  r2dbc:
    url: r2dbc:postgresql://localhost:5432/flow_dev
    username: flow_developer
    password: flowdev123
  data:
    redis:
      host: localhost
      port: 6379
      timeout: 2000ms
      connect-timeout: 2000ms
  webflux:
    base-path: /api
  security:
    filter:
      dispatcher-types: error,request
  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    consumer:
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      group-id: flow-backend
      auto-offset-reset: earliest
      properties:
        spring.json.trusted.packages: sg.flow.events

server:
  port: 8081
  servlet:
    context-path: /api

app:
  private-key:
    path: classpath:cert/private.pem
  public-key:
    path: classpath:cert/public.pem

logging:
  level:
    org.springframework.security: DEBUG
    io.r2dbc.spi: DEBUG
    org.springframework.r2dbc.connection: DEBUG

finverse-webclient:
  base-url: https://api.prod.finverse.net

finverse:
  webhook:
    publicKey: '-----BEGIN PUBLIC KEY-----\nMFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAEuZId/6U0gKLodSihwC/EuMGtULx8\nG3r7X7nZ3KWO5uNVtRTC64MH/1faq9zRp/2iIjCT8erSxiyO6y8wnlqMqw==\n-----END PUBLIC KEY-----'

flow:
  kafka:
    topics:
      finverse-webhook: finverse-webhook-events
      finverse-auth-callback: finverse-auth-callback-events
      finverse-timeout: finverse-timeout-events
      finverse-auth-complete: finverse-auth-complete-events
      finverse-product-complete: finverse-product-complete-events
      transaction-analysis-trigger: transaction-analysis-trigger
  transaction-analysis:
    batch-size: 25
    max-retries: 3
    retry-delay-ms: 1000
    enabled: true
    processing-timeout-ms: 300000
    max-concurrent-batches: 3

aws:
  region: us-east-1
  bedrock:
    region: us-east-1
    agent-id: N8IR2MXV8S
    agent-alias-id: DBQCGNKB7K
    session-id: transaction-analysis-session
    max-tokens: 8192
    temperature: 0.1
    timeout-ms: 30000
    max-retries: 3
    base-retry-delay-ms: 1000
    max-retry-delay-ms: 30000
