services:
  postgres:
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=zen_dev'
      - 'POSTGRES_PASSWORD=airbusa380861'
      - 'POSTGRES_USER=zen_developer'
    ports:
      - '5432'
  redis:
    image: 'redis:latest'
    ports:
      - '6379'
  
