services:
  postgres:
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=flow_dev'
      - 'POSTGRES_PASSWORD=flowdev123'
      - 'POSTGRES_USER=flow_developer'
    ports:
      - '5432:5432'
  redis:
    image: 'redis:latest'
    ports:
      - '6379'
  
